# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import functions
import variables
import utilities

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 30, 681, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.labelOutput = QtWidgets.QLabel(self.tab)
        self.labelOutput.setGeometry(QtCore.QRect(90, 280, 531, 71))
        self.labelOutput.setText("")
        self.labelOutput.setObjectName("labelOutput")
        self.loadButton = QtWidgets.QPushButton(self.tab)
        self.loadButton.setGeometry(QtCore.QRect(260, 130, 101, 51))
        self.loadButton.setObjectName("loadButton")
        self.labelSrc = QtWidgets.QLabel(self.tab)
        self.labelSrc.setGeometry(QtCore.QRect(90, 20, 71, 41))
        self.labelSrc.setObjectName("labelSrc")
        self.textSrc = QtWidgets.QTextEdit(self.tab)
        self.textSrc.setGeometry(QtCore.QRect(180, 30, 391, 31))
        self.textSrc.setObjectName("textSrc")
        self.textDest = QtWidgets.QTextEdit(self.tab)
        self.textDest.setGeometry(QtCore.QRect(180, 70, 391, 31))
        self.textDest.setObjectName("textDest")
        self.labelDst = QtWidgets.QLabel(self.tab)
        self.labelDst.setGeometry(QtCore.QRect(90, 60, 71, 41))
        self.labelDst.setObjectName("labelDst")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.previewLabel = QtWidgets.QLabel(self.tab_2)
        self.previewLabel.setGeometry(QtCore.QRect(40, 60, 301, 311))
        self.previewLabel.setText("")
        self.previewLabel.setScaledContents(True)
        self.previewLabel.setObjectName("previewLabel")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(420, 50, 201, 171))
        self.groupBox.setObjectName("groupBox")
        self.label1 = QtWidgets.QRadioButton(self.groupBox)
        self.label1.setGeometry(QtCore.QRect(30, 30, 82, 17))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QRadioButton(self.groupBox)
        self.label2.setGeometry(QtCore.QRect(30, 60, 82, 17))
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QRadioButton(self.groupBox)
        self.label3.setGeometry(QtCore.QRect(30, 90, 82, 17))
        self.label3.setObjectName("label3")
        self.otherCategoryLabel = QtWidgets.QTextEdit(self.groupBox)
        self.otherCategoryLabel.setGeometry(QtCore.QRect(50, 120, 121, 31))
        self.otherCategoryLabel.setObjectName("otherCategoryLabel")
        self.saveButton = QtWidgets.QPushButton(self.tab_2)
        self.saveButton.setGeometry(QtCore.QRect(460, 240, 75, 23))
        self.saveButton.setObjectName("saveButton")
        self.prevButton = QtWidgets.QPushButton(self.tab_2)
        self.prevButton.setGeometry(QtCore.QRect(70, 400, 111, 41))
        self.prevButton.setObjectName("prevButton")
        self.nextButton = QtWidgets.QPushButton(self.tab_2)
        self.nextButton.setGeometry(QtCore.QRect(210, 400, 111, 41))
        self.nextButton.setObjectName("nextButton")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # add functions here
        self.tabWidget.setCurrentIndex(0)
        self.loadButton.clicked.connect(self.clickMe)
        self.prevButton.clicked.connect(lambda: functions.clickPrev(self.previewLabel))
        self.nextButton.clicked.connect(lambda: functions.clickNext(self.previewLabel))
        self.saveButton.clicked.connect(self.clickSave)
        self.label1.clicked.connect(lambda: functions.clickRadioButton(0))
        self.label2.clicked.connect(lambda: functions.clickRadioButton(1))
        self.label3.clicked.connect(lambda: functions.clickRadioButton(2))

    def clickSave(self):
        variables.OTHER_CATEGORY_LABEL = self.otherCategoryLabel.toPlainText()
        functions.clickSave(self.previewLabel)

    def clickMe(self):
        variables.SRC_DIR = self.textSrc.toPlainText()
        variables.DEST_DIR = self.textDest.toPlainText()
        variables.IMAGE_LIST = utilities.getImageList(variables.SRC_DIR)
        variables.TOTAL_IMAGES = len(variables.IMAGE_LIST)
        functions.clickMe(self.labelOutput, self.previewLabel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "Load Images"))
        self.labelSrc.setText(_translate("MainWindow", "SRC_FOLDER"))
        self.labelDst.setText(_translate("MainWindow", "DEST_FOLDER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.groupBox.setTitle(_translate("MainWindow", "Labels"))
        self.label1.setText(_translate("MainWindow", "Tableware"))
        self.label2.setText(_translate("MainWindow", "Coffee Cup"))
        self.label3.setText(_translate("MainWindow", "Others"))
        self.saveButton.setText(_translate("MainWindow", "SAVE"))
        self.prevButton.setText(_translate("MainWindow", "PREV"))
        self.nextButton.setText(_translate("MainWindow", "NEXT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
